openapi: 3.0.3
info:
  title: Product API
  version: 1.0.0
paths:
  /products:
    post:
      summary: Create a new product
      operationId: createProduct
      tags:
        - products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductDetail"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDetail"
        '400':
          description: Invalid input

  /products/{productId}:
    get:
      summary: Get a product by ID
      tags:
        - products
      operationId: getProductById
      parameters:
        - name: productId
          in: path
          description: ID of the product to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDetail"
        '404':
          description: Product not found
components:
  schemas:
    ProductDetail:
      title: "ProductDetail"
      type: object
      properties:
        name:
          type: string
        category:
          type: string
        price:
          type: number
        description:
          type: string
